# Sequence Models & How to use them

**학습목표**
1. Conv1D 와 Maxpool1D의 사용법을 안다.
2. RNN과의 차이를 이해한다.

-----------------
* Thanks to : 한기영 대표님 @ Data Insight

## 1.환경 및 데이터 준비

### Import Packages

In [9]:
#라이브러리들을 불러오자.
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Flatten, MaxPool1D, Conv1D, LSTM, GRU, Bidirectional
from tensorflow.keras.models import Model

### Data Loading

In [10]:
url = 'https://raw.githubusercontent.com/RayleighKim/Example_datasets/master/Stock_Edwards_Lifesciences_corporation.csv'

# 판다스로 데이터를 불러오시오.
data = pd.read_csv(url)

In [11]:
data.head()

        Date      Open      High       Low     Close  Adj_Close   Volume
0  2000/3/27  3.812500  4.156250  3.812500  4.125000   4.125000  3675600
1  2000/3/28  4.125000  4.125000  4.000000  4.015625   4.015625  1077600
2  2000/3/29  4.000000  4.031250  3.953125  4.000000   4.000000   437200
3  2000/3/30  4.000000  4.000000  3.843750  3.843750   3.843750  1883600
4  2000/3/31  3.734375  3.734375  3.390625  3.390625   3.390625  7931600

##3.데이터 준비

### Date 컬럼을 제거하시오.

In [12]:
data = data.drop('Date', axis=1)

## 4.Sequence 데이터 구조로 만들기

**조건**
* 내일의 Close를 예측할 것이다. 이를 Y로 둘 것.
* timestep은 8주를 본다. (주식은 5일이 1주일)
* 맞추어 전처리

**데이터 분할 규칙**
* 가장 최근 1주일을 테스트 데이터로 둔다.
* 테스트 데이터를 제외하고, 가장 최근 2주를 벨리데이션 데이터로 둔다.

In [13]:
# 판다스 데이터 프레임을 넘파이로 옮김.
data = data.values

In [ ]:
# 여기에 의미있는 기간(timestep을 지정해 봅시다.)
timestep= 40




## 모양 확인 필수

데이터의 구조 : [n, timestep, feature수]

# 같이 해보기

1. 적절한 인풋 레이어를 구성할 것
2. Conv1D
    * 16개 필터 사용할 것
    * window_size(filter_size)는 5일
    * activation은 swish
3. Conv1D
    * 32개 필터 사용할 것
    * window size 는 2일
    * activation은 swish
3. MaxPool1D
    * 필터 사이즈(window size)는 2일
2. 세번째 히든레이어 : LSTM
    * 히든스테이트 노드 48개, return_sequences=True
3. 네번째 히든레이어 : LSTM
    * 히든스테이트 노드 64개, return_sequences=True
4. 플래튼
5. 회귀를 위한 적절한 아웃풋 레이어

In [ ]:
####################
## Your Code Here ##
####################

In [ ]:
## 학습도 시킬 것

In [ ]:
# Q1. 테스트 셋에서의 RMSE를 출력하여라.

## Q1. Conv1D와 함께하는 시퀀스 모델링

1. 적절한 인풋 레이어를 구성할 것
2. 첫번째 히든레이어 : Conv1D
    * 16개 필터 사용할 것
    * window_size(filter_size)는 2일
    * activation은 swish
3. 두번째 히든레이어 : MaxPool1D
    * 필터 사이즈(window size)는 2일
2. 세번째 히든레이어 : GRU
    * 히든스테이트 노드 32개, return_sequences=True
3. 네번째 히든레이어 : LSTM
    * 히든스테이트 노드 64개, return_sequences=True
4. 다섯번째 히든레이어 : Conv1D
    * 32개 필터 사용할 것.
    * window size는 5일
4. 플래튼
5. 회귀를 위한 적절한 아웃풋 레이어

In [ ]:
####################
## Your Code Here ##
####################

In [ ]:
## 학습도 시킬 것

In [ ]:
# Q1. 테스트 셋에서의 RMSE를 출력하여라.